create_user_table = '''CREATE TABLE IF NOT EXISTS USERS (
            ID INTEGER PRIMARY KEY NOT NULL,
            NAME VARCHAR(30) NOT NULL,
            EMAIL VARCHAR(30) NOT NULL,
            LOGINID VARCHAR(15) NOT NULL,
            PASSWD VARCHAR(15) NOT NULL,
            USERTYPE SMALLINT NOT NULL
        );'''


create_chassis_types_table = '''CREATE TABLE IF NOT EXISTS CHASSISTYPES (
CHASSISID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(20) NOT NULL
);'''

create_vehicles_table = '''CREATE TABLE IF NOT EXISTS VEHICLES (
VEHICLEID INTEGER PRIMARY KEY NOT NULL,
FLEETCODE VARCHAR(15) NOT NULL,
REGNUMBER VARCHAR(15) NOT NULL,
CHASSISID INTEGER
);'''


create_tyrelocation_table = '''CREATE TABLE IF NOT EXISTS TYRELOCATION (
TYREID INTEGER,
DATETICKS INTEGER,
DIRECTION SMALLINT,
VEHICLEID INTEGER
);'''

create_tyres_table = '''CREATE TABLE IF NOT EXISTS TYRES (
TYREID INTEGER PRIMARY KEY NOT NULL,
NAME VARCHAR(15),
SERIALNUM VARCHAR(15)
);'''

insert_user_data_statement = '''INSERT INTO USERS (NAME, EMAIL, LOGINID, PASSWD, USERTYPE)
VALUES (?, ?, ?, ?, ?)'''

insert_chassis_type_statement = '''INSERT INTO CHASSISTYPES (NAME) VALUES (?)'''

select_chassis_type_statement = '''SELECT * FROM CHASSISTYPES'''

select_vehicle_data_statement = '''SELECT VEHICLEID, FLEETCODE, REGNUMBER, CHASSISTYPES.NAME AS CHASSIS FROM VEHICLES JOIN CHASSISTYPES ON VEHICLES.CHASSISID=CHASSISTYPES.CHASSISID'''

insert_vehicle_data_statement = '''INSERT INTO VEHICLES (FLEETCODE, REGNUMBER, CHASSISID) VALUES (?, ?, ?)'''

select_tyre_data_statement = '''SELECT * FROM TYRES'''

insert_tyre_data_statement = '''INSERT INTO TYRES (NAME, SERIALNUM) VALUES (?, ?)'''

insert_tyre_location_data_statement = '''INSERT INTO TYRELOCATION (TYREID, DATETICKS, DIRECTION, VEHICLEID) VALUES (?, ?, ?, ?)'''

select_tyre_location_data_statement = '''SELECT DATETICKS, DIRECTION, TYRES.NAME AS TYRE_NAME, VEHICLES.REGNUMBER AS VEHICLE_REG FROM TYRELOCATION JOIN TYRES ON TYRES.TYREID=TYRELOCATION.TYREID JOIN VEHICLES ON VEHICLES.VEHICLEID=TYRELOCATION.VEHICLEID'''

update_user_profile_statement = '''UPDATE USERS SET NAME = ?, EMAIL = ?, LOGINID = ?, PASSWD = ? WHERE ID = ?'''

select_user_object_statement = '''SELECT * FROM USERS WHERE LOGINID = ? AND PASSWD = ?'''

select_user_object_by_id_statement = '''SELECT * FROM USERS WHERE ID = ?'''

select_tyre_journey_data_statement = '''SELECT TYRELOCATION.TYREID, CAST(( SELECT DATETICKS FROM TYRELOCATION JOIN CHASSISTYPES ON CHASSISTYPES.CHASSISID=VEHICLES.CHASSISID WHERE DIRECTION = 1 AND VEHICLES.VEHICLEID = TYRELOCATION.VEHICLEID)  - (SELECT DATETICKS FROM TYRELOCATION JOIN CHASSISTYPES ON CHASSISTYPES.CHASSISID=VEHICLES.CHASSISID WHERE DIRECTION = 0 AND VEHICLES.VEHICLEID = TYRELOCATION.VEHICLEID) AS DATE_DIFF) / 86400 AS DATEDIFF , VEHICLES.CHASSISID, CHASSISTYPES.NAME FROM TYRELOCATION JOIN CHASSISTYPES ON CHASSISTYPES.CHASSISID=(SELECT VEHICLES.CHASSISID FROM VEHICLES WHERE VEHICLES.VEHICLEID=TYRELOCATION.VEHICLEID) JOIN VEHICLES ON VEHICLES.VEHICLEID=TYRELOCATION.VEHICLEID GROUP BY VEHICLES.CHASSISID'''
 

